name: Call multiple reusable workflows

on:
  pull_request:
    branches:
      - main

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."

  call_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout custom reusable actions
        uses: actions/checkout@v2
        # with:
        #   repository: renansigolo-hf/masterfresh
        #   path: masterfresh

      - name: Use action
        uses: ./masterfresh/.github/actions/say-hello
        with:
          name: Renan

      # - uses: actions/checkout@v2
      # - uses: ./actions/say-hello@v1
      #   with:
      #     name: OctoCat

  # call_workflow_again:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: ${{ github.workspace }}/actions/say-hello@v1
  #       with:
  #         name: OctoCat
